name: CMake Build

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

env:
  BUILD_TYPE: Release
  GTEST_DIR: /home/runner/googletest

jobs:
  gtest-build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone GTest
        run: git clone https://github.com/google/googletest.git -b release-${{secrets.GTEST_VERSION}} ${{env.GTEST_DIR}} && cd ${{env.GTEST_DIR}}

      - name: Configure GTest
        run: cmake -B ${{env.GTEST_DIR}}/build -S ${{env.GTEST_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build GTest
        run: cmake --build ${{env.GTEST_DIR}}/build

      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: gtest_build
          path: ${{env.GTEST_DIR}}

  build:
    runs-on: ubuntu-latest
    needs: gtest-build

    steps:
      - name: Download GTest build artifacts
        uses: actions/download-artifact@v3
        with:
          name: gtest_build
          path: ${{env.GTEST_DIR}}

      - name: Install GTest
        run: cd ${{env.GTEST_DIR}} && sudo cmake --build ${{env.GTEST_DIR}}/build --target install

      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Run CTest
        working-directory: build
        run: ctest --output-on-failure
